# meta: alembic revision template (standard, trimmed).
"""flag trust signals

Revision ID: 6d48d50cc391
Revises: c3a91e07d412
Create Date: 2026-07-24 14:52:21.667288
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6d48d50cc391'
down_revision: Union[str, None] = 'c3a91e07d412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flags', sa.Column('evidence_valid', sa.Boolean(), nullable=True))
    op.add_column('flags', sa.Column('ambiguous', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flags', 'ambiguous')
    op.drop_column('flags', 'evidence_valid')
    # ### end Alembic commands ###
