"""
meta:
  purpose: VERBATIM scorecard rule text, GENERATED by extraction from
           doc 05 §1 (../05_shibboleth_problem_context_and_scorecard
           _2026-07-09.md) — never hand-edited (guardrail: no paraphrase).
           Severities per rule from the frozen ground truth distribution.
  contract: RULES: list of (rule_id, verbatim_text, severity, position);
            D01_APPROVED_TEXT: the approved disclosure from doc 05 §2.
            tests/unit/test_seed_verbatim.py re-extracts from doc 05 and
            asserts byte-for-byte equality. Regenerate, never edit.
  deps: none (data module).
"""

RULES: list[tuple[str, str, str, int]] = [
    ("R-01", 'If Turbotax free is mentioned, the following must be disclosed right underneath ~37% of filers qualify. [Simple Form 1040 returns only](https://turbotax.intuit.com/personal-taxes/online/free-edition.jsp#modals/simple-tax-returns-en) (no schedules, except for EITC, CTC, student loan interest, and Schedule 1-A).', "High", 1),
    ("R-02", 'If a rate of finance charge was stated, was the finance charge stated as an APR?', "High", 2),
    ("R-03", 'If the product being advertised is a deposit product, does the FDIC insurance language state Deposit product is FDIC-insured up to $250,000 through  Bank', "Medium", 3),
    ("R-04", 'If an institution states a bonus in an advertisement, does the advertisement state clearly and conspicuously the following information, if applicable to the advertised product: (1) "Annual percentage yield," using that term; (2) Time requirement to obtain the bonus; (3) Minimum balance required to obtain the bonus; (4) Minimum balance required to open the account, if it is greater than the minimum balance necessary to obtain the bonus; and (5) Time when the bonus will be provided? In addition, general statements such as "bonus checking" or "get a bonus when you open a checking account" do not trigger the bonus disclosures.', "Medium", 4),
]

D01_APPROVED_TEXT = '~37% of filers qualify. Simple Form 1040 returns only (no schedules, except for EITC, CTC, student loan interest, and Schedule 1-A).'
